package dev.sample.framework.test.dto.assertj;

import dev.sample.framework.test.dto.MulitpleTypeDto;

/**
 * {@link MulitpleTypeDto} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractMulitpleTypeDtoAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class MulitpleTypeDtoAssert extends AbstractMulitpleTypeDtoAssert<MulitpleTypeDtoAssert, MulitpleTypeDto> {

  /**
   * Creates a new <code>{@link MulitpleTypeDtoAssert}</code> to make assertions on actual MultipleTypeDto.
   * @param actual the MultipleTypeDto we want to make assertions on.
   */
  public MulitpleTypeDtoAssert(MulitpleTypeDto actual) {
    super(actual, MulitpleTypeDtoAssert.class);
  }

  /**
   * An entry point for MultipleTypeDtoAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myMultipleTypeDto)</code> and get specific assertion with code completion.
   * @param actual the MultipleTypeDto we want to make assertions on.
   * @return a new <code>{@link MulitpleTypeDtoAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static MulitpleTypeDtoAssert assertThat(MulitpleTypeDto actual) {
    return new MulitpleTypeDtoAssert(actual);
  }
}
