package dev.sample.framework.test.dto.assertj;

import dev.sample.framework.test.dto.MultipleTypeDto;

/**
 * {@link MultipleTypeDto} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractMultipleTypeDtoAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class MultipleTypeDtoAssert extends AbstractMultipleTypeDtoAssert<MultipleTypeDtoAssert, MultipleTypeDto> {

  /**
   * Creates a new <code>{@link MultipleTypeDtoAssert}</code> to make assertions on actual MultipleTypeDto.
   * @param actual the MultipleTypeDto we want to make assertions on.
   */
  public MultipleTypeDtoAssert(MultipleTypeDto actual) {
    super(actual, MultipleTypeDtoAssert.class);
  }

  /**
   * An entry point for MultipleTypeDtoAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myMultipleTypeDto)</code> and get specific assertion with code completion.
   * @param actual the MultipleTypeDto we want to make assertions on.
   * @return a new <code>{@link MultipleTypeDtoAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static MultipleTypeDtoAssert assertThat(MultipleTypeDto actual) {
    return new MultipleTypeDtoAssert(actual);
  }
}
